services:
    sylius-app:
        profiles: [ "disabled" ]

    sylius-mysql:
        ports:
            - 3306:3306

    mailpit:
        image: axllent/mailpit
        ports:
            - "8025:8025"
            - "1025:1025"
