# Delete these routes and define your own shop routes here

webgriffe_sylius_pagolight_static_welcome:
    path: /static-welcome/{name}
    defaults:
        _controller: Webgriffe\SyliusPagolightPlugin\Controller\GreetingController::staticallyGreetAction
        name: ~

webgriffe_sylius_pagolight_dynamic_welcome:
    path: /dynamic-welcome/{name}
    defaults:
        _controller: Webgriffe\SyliusPagolightPlugin\Controller\GreetingController::dynamicallyGreetAction
        name: ~
